name: Build and Publish Test Docker Image

on:
  push:
    branches: ["main"]
    # paths:
    #   - tools/hardware_test_runner/Dockerfile
    # joijoijoij
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    runs-on: HIL-Capable

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Log in to GitHub Container Registry
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # 3. Extract metadata (tags, labels)
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/hardware_test

      # 4. Build and push image
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: ./tools/hardware_test_runner
          file: ./tools/hardware_test_runner/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}