name: Build forth_shell
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Environment
        run: |
          sudo apt-get update
          sudo apt-get install -y rust
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: |
          cd tools/forth_shell
          cargo build --release

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: executables
          path: |
            ./tools/forth_shell/target/release/forth_shell



