name: Build ch32v203 elf file
on:
  push:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/jimmarshall35/risc-v-forth/toolchain:main 
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Build
        run: make
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ch32v203
          path: |
            Forth.elf
            Forth.map
            QEMUForth.elf

  












